# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VgLw2ZtOHOpcYHprey-qFFMdkUo7GuvF
"""

#  funtion define
def uniqueTypeCounter(employees,files):
  type_list=[]
  for i in range(len(employees)):
    for j in range(len(files)):
      if employees[i][0] == files[j][0] or employees[i][1] == files[j][0]:
        type_list.append(files[j][1])
        
  n = len(set(type_list))
  return n

# initialization of the Parameteter 
employees = [['1','Alice'],['2','John'],['3','Jane'],['4','Alice'],['5','Bob']]
files = [['100','jpeg'],['Alice','png'],['3','jpg'],['1','jpg'],['John','jpeg']]
#  calling the funtion
print(uniqueTypeCounter(employees,files))

